### ISSUE TITLE
Last sentence of Abstract could be clearer 

### ISSUE THREAD

**Issue by Homebush** [KantaraInitiative/DistributedAssurance#3]
This phrase "...to authenticate the user to any provider that is part of the same trust environment as the primary provider of identity assurance and the phone app provider of authentication assurance" could do with clarifying if both providers need to be present in the one and the same trust environment and neither of whom issued the credential in the first place.

**Comment by TomCJones** [comment]
how about
to authentication the user any provider that is a part of a trusted ecosystem. This specification will give an example of providers that are part of a healthcare ecosystem where all members have agreed to protect the user's privacy at strictly enforce high levels.

**Comment by TomCJones** [comment]
approved change at 2020-01-07 meeting
