### ISSUE TITLE
Add link for applicable IPR option for the FIRE WG

### ISSUE THREAD

**Issue by Homebush** [KantaraInitiative/DistributedAssurance#4]
In the footer, there is reference to Kantara IPR. Either use the following hyperlink, 
https://kantarainitiative.org/confluence/display/GI/Option+Non-Assertion+Covenant
or express specifically, 'Kantara IPR Option: Non Assertion Covenant'

**Comment by TomCJones** [comment]
made change at 2020-01-07 meeting
wait for Jeff to review.

**Comment by TomCJones** [comment]
approved 20-01-21
